set fileencodings=utf-8,ucs-bom,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set number
set cursorline
set autoindent
set tabstop=4
set showmode
syntax on
set t_Co=256
set showmatch
